### ISSUE TITLE
Vad händer när argement document inte har antingen title eller content?

### ISSUE THREAD

**Issue by olbr22** [maru23bth/jsramverk-backend#6]
https://github.com/maru23bth/jsramverk-backend/blob/0f53707e980b9fec8e404620b1f14217720a1106/db/mongodb.mjs#L75

**Comment by maru23bth** [comment]
Ändrat så title är required när nytt dokument skapas.
Content är fortfarande valbart.

Vid update så kan man fortfarande lämna både title och content tomt.
